Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,4 +1,4 @@
-# Stand: 2025-05-20_22:15
+# Stand: 2025-05-20_22:30
 workflows:
   android-workflow:
     name: Android Build
@@ -42,7 +42,7 @@ workflows:
       - name: Generate Gradle Wrapper
         script: |
           echo "Generating Gradle wrapper"
-          /tmp/gradle-8.3/bin/gradle wrapper --gradle-version 8.3 --distribution-type bin
+          /tmp/gradle-8.3/bin/gradle wrapper --gradle-version 8.3 --distribution-type bin || exit 1
           ls -l gradle/wrapper/
       - name: Set Execute Permissions
         script: |
@@ -56,9 +56,14 @@ workflows:
         script: |
           echo "Checking Gradle wrapper integrity"
           ls -l gradle/wrapper/
-          file gradle/wrapper/gradle-wrapper.jar
-          du -h gradle/wrapper/gradle-wrapper.jar
-          java -cp gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain --version
+          if [ -f gradle/wrapper/gradle-wrapper.jar ]; then
+            file gradle/wrapper/gradle-wrapper.jar
+            du -h gradle/wrapper/gradle-wrapper.jar
+            java -cp gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain --version
+          else
+            echo "Error: gradle-wrapper.jar not found"
+            exit 1
+          fi
       - name: Check Gradle Environment
         script: |
           java -version
